online_courses:
  help:
    mail: mailto:weilingooi62@gmail.com

links:
  manual_form_description: "#"
  gravatar: "https://secure.gravatar.com/avatar/"
  gravatar_email: "http://gravatar.com/emails"

validations:
  name:
    max_length: 50
  email:
    max_length: 50
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6
  course:
    max_length: 300

gravartar:
  size_default: 80
  size_list: 50

remember_me: 1

default_page:
  courses: 10
  users: 10

